/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_MyLib */

#ifndef _Included_main_java_MyLib
#define _Included_main_java_MyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_MyLib
 * Method:    mainFunc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_MyLib_mainFunc
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
